### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Diego910** [bq/aquaris-5HD#1]
En el readme deberia poner esto  git clone https://github.com/bq/aquaris-5HD.git para descargarlo correctamente

**Comment by mikelfer** [comment]
Ambas formas son posibles, depende de si tienes configurada tu clave ssh en tu cuenta de github.

Saludos.

**Comment by Diego910** [comment]
Ah ok gracias.  Pero acabo de probar a compilar y me da error, no encuentra la toolchain, puedes arreglarlo o decirme como definirla? He comparado un poco con el del a5 que si me compila pero no encuentro la diferencia
